name: Deploy API (FastAPI) to Azure Web App
on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/deploy-api.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api   # <- muy importante: trabajamos dentro de /api
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Empaquetar SOLO la carpeta /api y que quede como raíz del sitio
      - name: Package /api as root artifact
        run: |
          cd ..
          zip -r api.zip api -x "api/__pycache__/*" "api/.pytest_cache/*" "api/.venv/*" "api/.git/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nupzial-api'
          package: api.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3EC64E3F2259438394A2EB57847EC4C8 }}
