name: Deploy API (prod) to Azure Web App
on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/main_nupzial-api.yml'

env:
  AZURE_WEBAPP_NAME: "nupzial-api"   # ej. api-tuapp
  API_FOLDER: "api"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.API_FOLDER }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # (Opcional) tests aquí

      # --- Autenticación: elige UNA de las dos secciones ---

      # Opción A: OIDC (recomendada)
      # - name: Azure Login (OIDC)
      #   uses: azure/login@v2
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Opción B: Publish Profile (simple)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: .   # despliega SOLO la carpeta /api
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3EC64E3F2259438394A2EB57847EC4C8 }}

